uploads = []
outputs = []

[[generated]]
id = "pecfvmXy7pSmrvqkyh6Lb"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RAMyfBaGK17jaKvZ5rPqH"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "generated_image"

[[generated]]
id = "iW08YJx6FJAZAgmbq21JT"
uri = "file://artifacts/mobile/assets/images/tractor.png"
type = "image"
title = "red electric tractor"
