// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// UPDATED: 2026-01-12 - Updated with latest CloudFormation stack outputs from dev-SoftwareBackendStack

import { ResourcesConfig } from 'aws-amplify';

const config: ResourcesConfig = {
  API: {
    GraphQL: {
      endpoint:
        'https://md3jfqmlmbgspdqfgmxffhcwai.appsync-api.ap-south-1.amazonaws.com/graphql',
      region: 'ap-south-1',
      defaultAuthMode: 'userPool'
      ,
    },
  },
  Auth: {
    Cognito: {
      userPoolId: 'ap-south-1_8Eomi3ymZ',
      userPoolClientId: '52qfclofiusha1pumph6r8a8ee',
      identityPoolId: 'ap-south-1:82ed9f8c-f1c6-4e6d-b58c-4c4df93f1702',
      loginWith: {
        username: false,
        email: true,
        phone: true,
      },
      passwordFormat: {
        minLength: 8,
        requireLowercase: true,
        requireUppercase: true,
        requireNumbers: true,
        requireSpecialCharacters: true,
      },
      userAttributes: {
        email: {
          required: true,
        },
        phone_number: {
          required: true,
        },
        given_name: {
          required: false,
        },
        family_name: {
          required: false,
        },
        address: {
          required: false,
        },
      },
    },
  },
};

export default config;
